# Generated by Django 4.2.5 on 2023-10-11 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('nurses', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name=255)),
                ('last_visit', models.DateField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Scheduled'), (1, 'In Progress'), (2, 'Completed'), (3, 'Canceled')], default=0)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurses.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
