# Generated by Django 4.2.5 on 2023-10-14 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('address', models.CharField(verbose_name=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('appt_slot', models.DateTimeField()),
                ('reason', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Scheduled'), (1, 'In Progress'), (2, 'Completed'), (3, 'Canceled')], default=0)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
            ],
            options={
                'ordering': ['appt_slot'],
            },
        ),
    ]
